INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('SOLICITADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('APROBADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('RECHAZADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('PAGADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('CERRADO');