INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('SOLICITADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('APROBADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('RECHAZADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('PAGADO');
INSERT INTO ESTADO_PRESTAMO (ESTADO_PRESTAMO) VALUES ('CERRADO');

INSERT INTO TIPO_USUARIO (TIPO_USUARIO) VALUES ('CLIENTENATURAL');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO) VALUES ('CLIENTEJURIDICO');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO) VALUES ('CAJERO');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO) VALUES ('GERENTEOFICINA');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO) VALUES ('GERENTEGENERAL');

INSERT INTO TIPO_DOCUMENTO (TIPO_DOCUMENTO) VALUES ('CC');
INSERT INTO TIPO_DOCUMENTO (TIPO_DOCUMENTO) VALUES ('CE');
INSERT INTO TIPO_DOCUMENTO (TIPO_DOCUMENTO) VALUES ('REGISTROCIVIL');
INSERT INTO TIPO_DOCUMENTO (TIPO_DOCUMENTO) VALUES ('TI');

INSERT INTO TIPO_CUENTA (TIPO_CUENTA) VALUES ('AHORROS');
INSERT INTO TIPO_CUENTA (TIPO_CUENTA) VALUES ('CORRIENTE');
INSERT INTO TIPO_CUENTA (TIPO_CUENTA) VALUES ('AFC');

INSERT INTO ESTADO_CUENTA (ESTADO_CUENTA) VALUES ('CERRADA');
INSERT INTO ESTADO_CUENTA (ESTADO_CUENTA) VALUES ('ACTIVA');
INSERT INTO ESTADO_CUENTA (ESTADO_CUENTA) VALUES ('DESACTIVADA');

INSERT INTO TIPO_OPERACION (TIPO_OPERACION) VALUES ('CONSIGNAR');
INSERT INTO TIPO_OPERACION (TIPO_OPERACION) VALUES ('RETIRAR');
INSERT INTO TIPO_OPERACION (TIPO_OPERACION) VALUES ('TRANSFERIR');

INSERT INTO TIPO_PRESTAMO (TIPO_PRESTAMO) VALUES ('VIVIENDA');
INSERT INTO TIPO_PRESTAMO (TIPO_PRESTAMO) VALUES ('ESTUDIO');
INSERT INTO TIPO_PRESTAMO (TIPO_PRESTAMO) VALUES ('AUTOMOVIL');
INSERT INTO TIPO_PRESTAMO (TIPO_PRESTAMO) VALUES ('LIBRE INVERSION');

INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Colombiana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Mexicana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Argentina');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Brasilenia');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Venezolana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Peruana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Chilena');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Canadiense');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Francesa');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Alemna');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Italiana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Inglesa');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Rusa');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('China');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Japonesa');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Nigeriana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Argelina');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Australiana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Uruguaya');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Paraguay');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Boliviana');
INSERT INTO NACIONALIDAD (NOMBRE) VALUES ('Ecuatoriana');

COMMIT;
