CREATE TABLE USUARIO
(
    ID_USUARIO NUMBER,
    TIPO_DOCUMENTO VARCHAR2(30 CHAR) NOT NULL,
    NUMERO_DOCUMENTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) NOT NULL,
    NACIONALIDAD VARCHAR2(30 CHAR) NOT NULL,
    DIRECCION_FISICA VARCHAR2(100 CHAR) NOT NULL,
    DIRECCION_DIGITAL VARCHAR2(100 CHAR) NOT NULL,
    TELEFONO NUMBER NOT NULL,
    CODIGO_POSTAL NUMBER NOT NULL,
    TIPO_USUARIO VARCHAR2(30 CHAR) NOT NULL,
    
    
    CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO),
    CONSTRAINT USUARIO_FK_ID FOREIGN KEY (ID_USUARIO)
    REFERENCES DATOS_USUARIO(id_usuario),
    
    CONSTRAINT TIPO_DOCUMENTO_C FOREIGN  KEY (TIPO_DOCUMENTO)
    REFERENCES TIPO_DOCUMENTO(TIPO_DOCUMENTO),
    
    CONSTRAINT TIPO_USUARIO_C FOREIGN KEY (TIPO_USUARIO)
    REFERENCES TIPO_USUARIO(TIPO_USUARIO)
    
);

ALTER TABLE USUARIO
ADD ID_DATOS_USUARIO NUMBER;

ALTER TABLE USUARIO
ADD CONSTRAINT ID_DATOS_USUARIO_C FOREIGN KEY (ID_DATOS_USUARIO)
REFERENCES DATOS_USUARIO (ID_USUARIO);

CREATE SEQUENCE datos_usuario_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE DATOS_USUARIO (
    ID_USUARIO NUMBER DEFAULT datos_usuario_seq.NEXTVAL,
    LOGIN VARCHAR2(40 CHAR) NOT NULL,
    clave VARCHAR2(40 CHAR) NOT NULL,
    CONSTRAINT datos_usuario_pk PRIMARY KEY (ID_USUARIO)
); 

INSERT INTO datos_usuario (LOGIN, clave) VALUES ('rockstar', 'guitarhero');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('codingninja', 'coder123');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('bookworm', 'readingbooks');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('travelbug', 'worldtravel');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('coffeelover', 'coffeetime');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('musicaddict', 'melodyrocks');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('beachbum', 'sandandsun');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('moviebuff', 'popcornmovies');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('gamerguru', 'gaminglife');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('naturelover', 'treehugger');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('fitnessfanatic', 'workout321');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('petparent', 'furryfriend');
INSERT INTO datos_usuario (LOGIN, clave) VALUES ('artenthusiast', 'colorpalette');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (1, 'CC', 123456789, 'Juan Perez', 'Colombiana', 'Calle 123', 'jperez@email.com', 1234567890, 12345, 'CLIENTE NATURAL');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (2, 'CE', 987654321, 'Maria Rodriguez', 'Colombiana', 'Avenida 456', 'mrodriguez@email.com', 9876543210, 54321, 'CLIENTE JURIDICO');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (3, 'CC', 234567890, 'Luisa Martinez', 'Colombiana', 'Carrera 789', 'lmartinez@email.com', 2345678901, 67890, 'CAJERO');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (4, 'CE', 876543210, 'Carlos Gutierrez', 'Colombiana', 'Calle 012', 'cgutierrez@email.com', 8765432109, 98765, 'GERENTE DE OFICINA');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (5, 'TI', 345678901, 'Ana Lopez', 'Colombiana', 'Carrera 111', 'alopez@email.com', 3456789012, 11111, 'GERENTE GENERAL');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (6, 'CE', 345678901, 'John Smith', 'Estadounidense', '123 Main St', 'jsmith@email.com', 1234567890, 54321, 'CLIENTE NATURAL');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (7, 'CE', 678901234, 'Alice Johnson', 'Canadiense', '456 Maple Ave', 'ajohnson@email.com', 2345678901, 65432, 'CLIENTE JURIDICO');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (8, 'CE', 901234567, 'Michael Brown', 'Brit�nica', '789 Oak Blvd', 'mbrown@email.com', 3456789012, 76543, 'CAJERO');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (9, 'CE', 234567890, 'Sophie Martinez', 'Francesa', '101 Elm St', 'smartinez@email.com', 4567890123, 87654, 'GERENTE DE OFICINA');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (10, 'CE', 567890123, 'Emily Jones', 'Australiana', '202 Pine St', 'ejones@email.com', 5678901234, 98765, 'GERENTE GENERAL');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (11, 'CC', 4546546, 'Daniel Roa', 'Colombiana', '123 casita St', 'dRosa@email.com', 111111, 54321, 'GERENTE DE OFICINA');

INSERT INTO USUARIO (ID_USUARIO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE, NACIONALIDAD, DIRECCION_FISICA, DIRECCION_DIGITAL, TELEFONO, CODIGO_POSTAL, TIPO_USUARIO)
VALUES (12, 'CC', 4546546, 'Andres Mendoza ', 'Colombiana', '123 casita St2', 'AMendoza@email.com', 132134, 543421, 'GERENTE DE OFICINA');

UPDATE USUARIO
SET ID_DATOS_USUARIO = 1
WHERE ID_USUARIO=1;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 2
WHERE ID_USUARIO=2;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 3
WHERE ID_USUARIO=3;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 4
WHERE ID_USUARIO=4;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 5
WHERE ID_USUARIO=5;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 6
WHERE ID_USUARIO=6;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 7
WHERE ID_USUARIO=7;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 8
WHERE ID_USUARIO=8;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 9
WHERE ID_USUARIO=9;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 10
WHERE ID_USUARIO=10;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 11
WHERE ID_USUARIO=11;

UPDATE USUARIO
SET ID_DATOS_USUARIO = 12
WHERE ID_USUARIO=12;